services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=mvc
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "5557:3306"


volumes:
  db-store:
    driver: local

